{{- if .Values.new_version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.image.green_tag }}
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      version: {{ .Values.image.green_tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.green_tag }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.green_tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
{{- end }}
