apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.name }}
  subsets:
  - name: {{ .Values.image.blue_tag }}
    labels:
      version: {{ .Values.image.blue_tag }}
  - name: {{ .Values.image.green_tag }}
    labels:
      version: {{ .Values.image.green_tag }}
