apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.name }}-gateway
  http:
    - route:
      - destination:
          host: {{ .Values.name }}
          subset: {{ .Values.image.blue_tag }}
        weight: {{ .Values.blue_weight }}
      - destination:
          host: {{ .Values.name }}
          subset: {{ .Values.image.green_tag }}
        weight: {{ .Values.green_weight }}
