name: test
namespace: test
replicaCount: 1

blue_version: true
blue_weight: 100
green_version: false
green_weight: 0

image:
  repository: janakiramm/myapp
  pullPolicy: IfNotPresent
  blue_tag: "v1"
  green_tag: "v2"

service:
  type: ClusterIP
  port: 80
