name: test
namespace: test
replicaCount: 1
blue_weight: 50
green_weight: 50

new_version: true

image:
  repository: janakiramm/myapp
  pullPolicy: IfNotPresent
  blue_tag: "v1"
  green_tag: "v2"

service:
  type: ClusterIP
  port: 80
